### ISSUE TITLE
infografia actividad1 unidad2

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/infografia-de-las-librerias-ang3-l32#2]
[UNIDAD 2 ACT1 INFOGRAFIA DE LIBRERIAS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-ang3-l32/files/8219752/UNIDAD.2.ACT1.INFOGRAFIA.DE.LIBRERIAS.pdf)

**Comment by Yareli-Perez** [comment]
calificación = 20 = 20%

**Comment by josealfredo79** [comment]
bien hecho y revisado...
